=== salvatorio/EPAM_Project_3/src/xml/Candy.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema
            attributeFormDefault="unqualified"
            elementFormDefault="qualified"
            xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Candy">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Candies" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Name"/>
                            <xs:element name="Energy"/>
                            <xs:element name="Type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="caramel"/>
                                        <xs:enumeration value="lollipop caramel"/>
                                        <xs:enumeration value="chocolate with filling"/>
                                        <xs:enumeration value="coconut with filling"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Water">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Sugar">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Fructose">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Vanillin">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Value">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Proteins">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Fats">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Carbohydrates">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:double">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="Production"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== salvatorio/EPAM_Project_3/src/xml/Candy.xml
<?xml version="1.0" encoding="UTF-8"?>

<Candy
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="Candy.xsd">
    <Candies id = "c1">
        <Name>Capri</Name>
        <Energy>402</Energy>
        <Type>caramel</Type>
        <Ingredients>
            <Water>500</Water>
            <Sugar>1200</Sugar>
            <Fructose>250</Fructose>
            <Vanillin>50</Vanillin>
        </Ingredients>
        <Value>
            <Proteins>0.5</Proteins>
            <Fats>4.8</Fats>
            <Carbohydrates>89.5</Carbohydrates>
        </Value>
        <Production>Roshen</Production>
    </Candies>

    <Candies id = "c2">
        <Name>Barbaris</Name>
        <Energy>390</Energy>
        <Type>lollipop caramel</Type>
        <Ingredients>
            <Water>450</Water>
            <Sugar>1000</Sugar>
            <Fructose>210</Fructose>
            <Vanillin>150</Vanillin>
        </Ingredients>
        <Value>
            <Proteins>0.1</Proteins>
            <Fats>0.3</Fats>
            <Carbohydrates>97.1</Carbohydrates>
        </Value>
        <Production>Roshen</Production>
    </Candies>

    <Candies id = "c3">
        <Name>Korivka</Name>
        <Energy>351</Energy>
        <Type>chocolate with filling</Type>
        <Ingredients>
            <Water>580</Water>
            <Sugar>1260</Sugar>
            <Fructose>350</Fructose>
            <Vanillin>40</Vanillin>
        </Ingredients>
        <Value>
            <Proteins>2.7</Proteins>
            <Fats>4.4</Fats>
            <Carbohydrates>82.4</Carbohydrates>
        </Value>
        <Production>Roshen</Production>
    </Candies>

    <Candies id = "c4">
        <Name>Raffaello</Name>
        <Energy>623</Energy>
        <Type>coconut with filling</Type>
        <Ingredients>
            <Water>130</Water>
            <Sugar>1570</Sugar>
            <Fructose>490</Fructose>
            <Vanillin>160</Vanillin>
        </Ingredients>
        <Value>
            <Proteins>9.3</Proteins>
            <Fats>47.8</Fats>
            <Carbohydrates>38.8</Carbohydrates>
        </Value>
        <Production>Ferrero</Production>
    </Candies>

    <Candies id = "c5">
        <Name>Royal charm</Name>
        <Energy>556</Energy>
        <Type>chocolate with filling</Type>
        <Ingredients>
            <Water>240</Water>
            <Sugar>2060</Sugar>
            <Fructose>150</Fructose>
            <Vanillin>270</Vanillin>
        </Ingredients>
        <Value>
            <Proteins>7.9</Proteins>
            <Fats>38</Fats>
            <Carbohydrates>47</Carbohydrates>
        </Value>
        <Production>AVK</Production>
    </Candies>
</Candy>
